learning_log/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('learning_logs.urls')),
    path('users/', include('users.urls')),
]

learning_logs/urls.py
"""Определяет схемы URL для learning_logs"""
from django.urls import path
from . import views

app_name = 'learning_logs'

urlpatterns = [
        #домашняя страница
        path('', views.index,name='index'),
        path('topics/',views.topics, name='topics'), 
        path('topics/<int:topic_id>/', views.topic, name='topic'),
        path('new_topic/', views.new_topic,name='new_topic'),
        path('new_entry/<int:topic_id>/',views.new_entry, name='new_entry'),
        path('edit_entry/<int:entry_id>/',views.edit_entry, name='edit_entry'),
        ]

users/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LoginView

app_name = 'users'

urlpatterns = [
        #домашняя страница
        path('login/',LoginView.as_view(template_name='users/login.html'), name='login'),
        path('logout/', views.logout_view, name='logout'),
        path('register/', views.register, name='register'),

        ] 

learning_logs/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Topic(models.Model):
    """ Тема """
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User,on_delete=models.CASCADE,)

    def __str__(self):
        """Возвращает строковое представление модели """
        return self.text

class Entry(models.Model):
    """Информация, изученная пользователем по теме"""
    topic = models.ForeignKey(Topic,on_delete=models.CASCADE,)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'entries'

    def __str__(self):
        """Возвращает строковое значение модели"""
        return self.text[:50] + "..."
    

users/models.py
from django.db import models

# Create your models here.

learning_logs/forms.py
from django import forms
from .models import Topic, Entry

class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['text']
        labels = {'text':''}
class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text': ''}
        widgets = {'text': forms.Textarea(attrs={'cols':80})}

learning_logs/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, Http404
from django.urls import reverse
from django.contrib.auth.decorators import login_required

from .models import Topic, Entry
from .forms import TopicForm, EntryForm

# Create your views here.

def index(request):
    """Домашняя страница приложения learning_log"""
    return render(request, 'learning_logs/index.html')

@login_required
def topics(request):
    """Выводит список тем """
    topics = Topic.objects.filter(owner=request.user).order_by('date_added')
    context = {'topics':topics}
    return render(request, 'learning_logs/topics.html', context)

@login_required
def topic(request, topic_id):
    """ Выводит одну тему и все её записи """
    topic = Topic.objects.get(id = topic_id)
    #Проверка того, что тема принадлежит текущему пользователю
    if topic.owner != request.user:
        raise Http404
    entries = topic.entry_set.order_by('-date_added')
    context = {'topic':topic, 'entries':entries}
    return render(request, 'learning_logs/topic.html', context)

@login_required
def new_topic(request):
    """Определяет новую тему"""
    if request.method != 'POST':
        # Данные не отправлялись, создается пустая форма
        form = TopicForm()
    else:
        # Отправлены данные POST, обработать данные
        form = TopicForm(data = request.POST)
        if form.is_valid():
            new_topic = form.save(commit=False)
            new_topic.owner = request.user
            new_topic.save()
            return HttpResponseRedirect(reverse('learning_logs:topics'))

    context = {'form':form}
    return render(request, 'learning_logs/new_topic.html', context)
 
@login_required
def new_entry(request, topic_id):
    """Определяет новую запись в конкретной теме """
    topic = Topic.objects.get(id = topic_id)

    if request.method != 'POST':
        # Данные не отправлялись, создается пустая форма
        form = EntryForm()
    else:
        # Отправлены данные POST, обработать данные
        form = EntryForm(data = request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            new_entry.save()
            return HttpResponseRedirect(reverse('learning_logs:topic', args=[topic_id]))

    context = {'topic':topic, 'form':form}
    return render(request, 'learning_logs/new_entry.html', context)
                    
@login_required
def edit_entry(request, entry_id):
    """Редактирует существующую запись"""
    entry = Entry.objects.get(id = entry_id)
    topic = entry.topic 
    if topic.owner != request.user:
        raise Http404

    if request.method != 'POST':
        #Исходный запрос, форма заполняется данными текущей записи 
        form = EntryForm(instance=entry)
    else:
        # Отправлены данные POST, обработать данные
        form = EntryForm(instance=entry, data = request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('learning_logs:topic', args=[topic.id]))

    context = {'entry':entry, 'topic':topic, 'form':form}
    return render(request, 'learning_logs/edit_entry.html', context)
 
    

users/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth import login,logout,authenticate
from django.contrib.auth.forms import UserCreationForm

# Create your views here.

def logout_view(request):
    """Завершает сеанс работы с приложением"""
    logout(request)
    return HttpResponseRedirect(reverse('learning_logs:index'))

def register(request):
    """Регистрирует нового пользователя"""
    if request.method != 'POST':
        #Показать пустую форму регистрации
        form = UserCreationForm()
    else:
        #Обработка заполненной формы
        form = UserCreationForm(data=request.POST)

        if form.is_valid():
            new_user = form.save()
            #Выполнение входа и перенаправление на домашнюю страницу
            authenticated_user = authenticate(username=new_user.username, password=request.POST['password1'])
            login(request, authenticated_user)
            return HttpResponseRedirect(reverse('learning_logs:index'))
    context = {'form':form}
    return render(request, 'users/register.html', context)

learning_logs/templates/learning_logs/base.html
<p>
	<a href="{% url 'learning_logs:index' %}">Learning Log</a>
	<a href="{% url 'learning_logs:topics' %}">Topics</a>
	{% if user.is_authenticated %}
	  Hello, {{ user.username }}.
	  <a href="{% url 'users:logout' %}">log out</a>
	{% else %}
	
	  <a href="{% url 'users:register' %}">register</a>
	  <a href="{% url 'users:login' %}">log in</a>
	{% endif %}
</p>
{% block content %}{% endblock content %}

learning_logs/templates/learning_logs/edit_entry.html
{% extends "learning_logs/base.html" %}
{% block content %}

<p><a href="{% url 'learning_logs:topic' topic.id %}">{{topic}}</a></p>

	<p> Edit entry</p>
	<form action ="{% url 'learning_logs:edit_entry' entry.id %}" method='post'>
		{% csrf_token %}
		{{ form.as_p }}
		<button name = "submit">save changes</button>
	</form>
{% endblock content %}

learning_logs/templates/learning_logs/index.html
{% extends "learning_logs/base.html" %}

{% block content %}

<p>Learning Log helps you keep track of your learning, for any topic you're learning about.</p>

{% endblock content %}

learning_logs/templates/learning_logs/new_entry.html
{% extends "learning_logs/base.html" %}
{% block content %}

<p><a href="{% url 'learning_logs:topic' topic.id %}">{{topic}}</a></p>

	<p>Add new entry</p>
	<form action ="{% url 'learning_logs:new_entry' topic.id %}" method='post'>

		{% csrf_token %}
		{{ form.as_p }}
		<button name = "submit">add entry</button>
	</form>
{% endblock content %}

learning_logs/templates/learning_logs/new_topic.html
{% extends "learning_logs/base.html" %}
{% block content %}
	<p>Add new topic</p>
	<form action ="{% url 'learning_logs:new_topic' %}" method='post'>
		{% csrf_token %}
		{{ form.as_p }}
		<button name = "submit">add topic</button>
	</form>
{% endblock content %}

learning_logs/templates/learning_logs/topic.html
{% extends 'learning_logs/base.html' %}

{% block content %}

	<p>Topic: {{ topic }}</p>

	<p>Entries:</p>
	<p>
	<a href="{% url 'learning_logs:new_entry' topic.id %}">add new entry</a>
	</p>
	<ul>
	{% for entry in entries %}
		<li>
			<p>{{ entry.date_added|date:'M d, Y H:i' }}</p>
			<p>{{ entry.text|linebreaks }}</p>
			<p>
			<a href="{% url 'learning_logs:edit_entry' entry.id %}">edit entry</a>
			</p>
		</li>
	{% empty %}
		<li>
			There are no entries for this topic yet.
		</li>
	{% endfor %}
	</ul>

{% endblock content %}

learning_logs/templates/learning_logs/topics.html
{% extends "learning_logs/base.html" %}

{% block content %}

  <p>Topics</p>

  <ul>
    {% for topic in topics %}
      <li>
        <a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a>
      </li>
    {% empty %}
      <li>No topics have been added yet.</li>
    {% endfor %}
  </ul>
  <a href="{% url 'learning_logs:new_topic' %}">Add a new topic:</a>


{% endblock content %}

users/templates/users/login.html
{% extends "learning_logs/base.html" %}
{% block content %}
  {% if form.errors %}
  <p>Your username and password didn't match. Please try again.</p>
  {% endif %}

  <form method="post" action="{% url 'users:login' %}">
  {% csrf_token %}
  {{ form.as_p }}

  <button name="submit">log in</button>
  <input type="hidden" name="next" value="{% url 'learning_logs:index' %}" />
  </form>

{% endblock content %}

users/templates/users/register.html
{% extends "learning_logs/base.html" %}
{% block content %}

  <form method="post" action="{% url 'users:register' %}">
  {% csrf_token %}
  {{ form.as_p }}

  <button name="submit">register</button>
  <input type="hidden" name="next" value="{% url 'learning_logs:index' %}" />
  </form>

{% endblock content %}